#!/usr/bin/env bash

pushd "$(dirname "$0")/../../genny/" >/dev/null
    GENNY_REPO_ROOT="$(pwd -P)"
    export GENNY_REPO_ROOT
popd >/dev/null

pushd "$(dirname "$0")/.." >/dev/null
    WORKLOAD_REPO_ROOT="$(pwd -P)"
    export WORKLOAD_REPO_ROOT
popd >/dev/null

"${GENNY_REPO_ROOT}/run-genny" "auto-tasks" "--workload-repo" "${WORKLOAD_REPO_ROOT}"
