qe_test_gen is a python program which generates Genny workloads for Queryable Encryption.

* Prerequisites
Install Poetry, following by [[https://python-poetry.org/docs/#installation][their documentation]] for one of the supported installation methods.

Then, using this directory as your current working directory, invoke Poetry to install the required dependencies into your local virtual environment, using the specific versions enumerated in =poetry.lock=.
#+BEGIN_SRC sh
poetry install
#+END_SRC

* Usage
Generate tests and runtime requirements by invoking qe_test_gen as follows:

#+BEGIN_SRC sh
poetry run python qe_test_gen/medical.py
#+END_SRC

This command will create:
- maps_medical.yml :: This file describes the data distributions for all fields. Genny will use this file to load data into the database.
- <data distribution>.txt :: These files contain all the possible values which a particular field may contain. Workloads will use these files to issue queries which are guaranteed to return a matching document.
- workload/*.yml :: Each of these files represent a workload. They must be copied from this directory, into a path which Genny will scan in Evergreen.
- patchConfig.yml :: *Most* of a YAML file which perf_tooling can use to download performance metrics. At a minimum, you'll need to edit in the Patch ID from an Evergreen patch you put up.
