SchemaVersion: 2018-07-01
Owner: Storage Execution
SlackSupportChannelName: "#server-storage-execution"
SlackSupportChannelId: C2RCHGB2L
Description: |
  Configuration for the MultiDeletes workload.

InitializeDatabaseOps:
- OperationName: RunCommand
  OperationCommand: {dropDatabase: 1}
