SchemaVersion: 2018-07-01
Owner: "@mongodb/server-execution"
Description: |
  Configuration for the MultiDeletes workload.

InitializeDatabaseOps:
- OperationName: RunCommand
  OperationCommand: {dropDatabase: 1}
