SchemaVersion: 2018-07-01
Owner: Storage Execution
Description: |
  Configuration for the MultiDeletes workload.

InitializeDatabaseOps:
  - OperationName: RunCommand
    OperationCommand: {dropDatabase: 1}
