#!/usr/bin/env bash
# Runs the genny python wrapper in the venv which runs the binary.

set -eou pipefail

pushd "$(dirname "$0")" >/dev/null
    LAMP_VENV_DIR="$(pwd -P)"
popd > /dev/null

source "$LAMP_VENV_DIR/env.sh"

# 'genny' is the python wrapper here.
genny "$@"
