#!/usr/bin/env bash
# Runs the canary python wrapper in the venv which runs the binary.

set -eou pipefail

pushd "$(dirname "$0")" >/dev/null
    LAMP_VENV_DIR="$(pwd -P)"
popd > /dev/null

source "$SCRIPTS_DIR/env.sh"

genny-canaries "$@"
