#!/usr/bin/env bash
# Because genies come from lamps.

set -eou pipefail

pushd "$(dirname "$0")" >/dev/null
    export LAMP_VENV_DIR="$(pwd -P)"
popd > /dev/null

source "$LAMP_VENV_DIR/env.sh"

python3 "$LAMP_VENV_DIR/../src/lamplib" "$@"

