#!/usr/bin/env bash
# Because genies come from lamps.

set -eou pipefail

pushd "$(dirname "$0")" >/dev/null
    export SCRIPTS_DIR="$(pwd -P)"
popd > /dev/null

source "$SCRIPTS_DIR/env.sh"

python3 "$SCRIPTS_DIR/../src/lamplib" "$@"

